version: '3.9'

networks:
  gringotts:
    name: gringotts
  traefik_proxy:
    external: true
  postgres:
    external: true

services:
  gringotts-core:
    image: 'ghcr.io/ivarrace/gringotts-core:0.0.2-snapshot'
    container_name: gringotts-core
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - gringotts
      - postgres
      - traefik_proxy
    environment:
      - SERVER_FORWARD-HEADERS-STRATEGY=framework #delete for next release
      - SERVER_SERVLET_CONTEXT-PATH=/api #Updated for traefik route
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DATASOURCE_HOST}/${DATASOURCE_DB}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - IVARRACE_JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./logs:/logs
    labels:
      # Proxy
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.gringotts-core.rule=Host(`gringotts.ivarrace.com`) && (PathPrefix(`/api`))"
      - "traefik.http.routers.gringotts-core.entrypoints=websecure"
      - "traefik.http.routers.gringotts-core.tls=true"
