version: '3.9'

services:

  gringotts-web:
    image: 'ghcr.io/ivarrace/gringotts-web:0.0.0'
    container_name: gringotts-web
    restart: unless-stopped
    depends_on:
      - gringotts-api
    ports:
      - '8082:80'

  gringotts-api:
    image: 'ghcr.io/ivarrace/gringotts-core:0.0.1-snapshot'
    build:
      context: .
    container_name: gringotts-api
    restart: unless-stopped
    depends_on:
      - gringotts-db
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gringotts-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
          
  gringotts-db:
    image: 'postgres:13.1-alpine'
    container_name: gringotts-db
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}